num_workers: 4
accelerator: 'auto'
num_epochs: 10
batch_size: 32
learning_rate: 0.001
model_name: 'resnet50'
num_classes: 11
data_dir: './data/weather-dataset'
wandb_name: 'resnet50'
wandb_project: 'compare-models'
wandb_entity: 'dl25-weather'