num_workers: 1
accelerator: 'auto'
num_epochs: 10
batch_size: 32
learning_rate: 0.00001
model_name: 'swin'
num_classes: 11
val_before_train: True

data_dir: './data/weather-dataset'

wandb_name: 'swin'
wandb_project: 'compare-models'
wandb_entity: 'dl25-weather'