num_workers: 4
accelerator: 'auto'
num_epochs: 20
batch_size: 32
learning_rate: 0.0001
lr_step_size: 100
lr_gamma: 0.8
model_name: 'swin'
num_classes: 11
val_before_train: True
early_stopping: True
early_stopping_patience: 4
early_stopping_metric: 'val_acc'
early_stopping_mode: 'max'
early_stopping_delta: 0.001

data_dir: './data/weather-dataset'
use_class_weights: True
save_model: True
save_model_path: './models'

wandb_name: 'swin'
wandb_project: 'compare-models'
wandb_entity: 'dl25-weather'