num_workers: 1
accelerator: 'auto'
num_epochs: 10
batch_size: 32
learning_rate: 0.0001
model_name: 'resnet50'
num_classes: 11
val_before_train: True
early_stopping: True
early_stopping_patience: 3
early_stopping_metric: 'val_loss'
early_stopping_mode: 'min'
early_stopping_delta: 0.001

data_dir: './data/weather-dataset'

wandb_name: 'resnet50'
wandb_project: 'compare-models'
wandb_entity: 'dl25-weather'