num_workers: 4
accelerator: 'auto'
num_epochs: 10
batch_size: 32
learning_rate: 0.0001
model_name: 'efficientnetb1'
num_classes: 11
val_before_train: True

data_dir: './data/weather-dataset'

wandb_name: 'efficientnetb1'
wandb_project: 'compare-models'
wandb_entity: 'dl25-weather'