num_workers: 4
accelerator: 'auto'
num_epochs: 20
batch_size: 32
learning_rate: 0.001
lr_step_size: 200
lr_gamma: 0.5
model_name: 'resnet50'
num_classes: 11
val_before_train: True
early_stopping: True
early_stopping_patience: 3
early_stopping_metric: 'val_loss'
early_stopping_mode: 'min'
early_stopping_delta: 0.001

data_dir: './data/weather-dataset'
use_class_weights: True
save_model: True
save_model_path: './models'

wandb_name: 'resnet50'
wandb_project: 'compare-models'
wandb_entity: 'dl25-weather'